In [26]:
import pandas as pd

In [27]:
import os
import re

allFilePaths = []

yearList = [int(x) for x in os.listdir('../assets')]

yearList.sort()

# yearList = yearList[:4]

In [28]:

for year in yearList:
    with os.scandir('../assets/'+str(year)) as it:
        for entry in it:
            if entry.name.endswith('.csv') and entry.is_file():
                filename = entry.name
                path = '../assets/'+str(year)+'/'+filename
                print(path)
                allFilePaths.append(path)

../assets/2016/output-05jun2k16annex5.csv
../assets/2016/output-10nov2k16annex5.csv
../assets/2016/output-07aug2k16annex5.csv
../assets/2016/output-03apr2k16annex5.csv
../assets/2016/output-02mar2k16annex5.csv
../assets/2016/output-09oct2k16annex5.csv
../assets/2016/output-00jan2k16annex5.csv
../assets/2016/output-11dec2k16annex5.csv
../assets/2016/output-04may2k16annex5.csv
../assets/2016/output-01feb2k16annex5.csv
../assets/2016/output-06jul2k16annex5.csv
../assets/2016/output-08sep2k16annex5.csv
../assets/2017/output-01feb2k17annex5.csv
../assets/2017/output-07aug2k17annex5.csv
../assets/2017/output-03apr2k17annex5.csv
../assets/2017/output-05jun2k17annex5.csv
../assets/2017/output-08sep2k17annex5.csv
../assets/2017/output-04may2k17annex5.csv
../assets/2017/output-10nov2k17annex5.csv
../assets/2017/output-09oct2k17annex5.csv
../assets/2017/output-06jul2k17annex5.csv
../assets/2017/output-00jan2k17annex5.csv
../assets/2017/output-02mar2k17annex5.csv
../assets/2017/output-11dec2k17annex5.csv
../assets/2018/output-11dec2k18annex5.csv
../assets/2018/output-07aug2k18annex5.csv
../assets/2018/output-02mar2k18annex5.csv
../assets/2018/output-10nov2k18annex5.csv
../assets/2018/output-04may2k18annex5.csv
../assets/2018/output-00jan2k18annex5.csv
../assets/2018/output-06jul2k18annex5.csv
../assets/2018/output-03apr2k18annex5.csv
../assets/2018/output-05jun2k18annex5.csv
../assets/2018/output-01feb2k18annex5.csv
../assets/2018/output-08sep2k18annex5.csv
../assets/2018/output-09oct2k18annex5.csv
../assets/2019/output-05jun2k19annex5.csv
../assets/2019/output-10nov2k19annex5.csv
../assets/2019/output-03apr2k19annex5.csv
../assets/2019/output-02mar2k19annex5.csv
../assets/2019/output-06jul2k19annex5.csv
../assets/2019/output-11dec2k19annex5.csv
../assets/2019/output-00jan2k19annex5.csv
../assets/2019/output-01feb2k19annex5.csv
../assets/2019/output-07aug2k19annex5.csv
../assets/2019/output-09oct2k19annex5.csv
../assets/2019/output-08sep2k19annex5.csv
../assets/2019/output-04may2k19annex5.csv
../assets/2020/output-03apr2k20annex5.csv
../assets/2020/output-00jan2k20annex5.csv
../assets/2020/output-02mar2k20annex5.csv
../assets/2020/output-01feb2k20annex5.csv

In [29]:
regions = ['EASTERN', 'WESTERN', 'SOUTHERN', 'NORTHEN', 'NORTH EAST']

In [30]:
headers = [x for x in range(19)]

In [31]:
ix_to_month = {
    '00':"Jan",
    '01':"Feb",
    '02':"Mar",
    '03':"Apr",
    '04':"May",
    '05':"Jun",
    '06':"Jul",
    '07':"Aug",
    '08':"Sep",
    '09':"Oct",
    '10':"Nov",
    '11':"Dec"
    
}

In [32]:
def separate_csv(path, col):
    df = pd.read_csv(path, names = headers, index_col=False  )
    
    movement = df.iloc[4:4+len(regions)]
    passengers = df.iloc[11:11+len(regions)]
    freight = df.iloc[18:18+len(regions)]
    
    movement_I, movement_D = cleanup(movement, "m", col)
    passengers_I, passengers_D = cleanup(passengers, "p", col)
    freight_I, freight_D = cleanup(freight, "f", col)
    
    return movement_I, movement_D, passengers_I, passengers_D, freight_I, freight_D
#     print(movement.shape)
#     print(passengers.shape)
#     print(freight.shape)

In [33]:
def cleanup(dataframe, name, alt):
    dataframe_I = dataframe.loc[:,[0,1]]
    dataframe_D = dataframe.loc[:,[0,7]]
    
    dataframe_I.set_index(0, inplace=True)
    dataframe_D.set_index(0, inplace=True)
    
    dataframe_I.rename(columns={1:str(alt+"_I")}, inplace=True)
    dataframe_D.rename(columns={7:str(alt+"_D")}, inplace=True)
    
#     print(dataframe.columns)
#     if name=="m":
#         print(dataframe)
        
    return dataframe_I, dataframe_D

../assets/2017/output-9oct2k17annex5.csv

In [34]:
movement_I_df = pd.DataFrame(index=regions, columns = ['hi', 'bi'])
passengers_I_df = pd.DataFrame(index=regions, columns = ['hi', 'bi'])
freight_I_df = pd.DataFrame(index=regions, columns = ['hi', 'bi'])

movement_D_df = pd.DataFrame(index=regions, columns = ['hi', 'bi'])
passengers_D_df = pd.DataFrame(index=regions, columns = ['hi', 'bi'])
freight_D_df = pd.DataFrame(index=regions, columns = ['hi', 'bi'])

In [35]:

for ix, filepath in enumerate(allFilePaths):
    filename = filepath[15:]
#     print(filename)
    year = filepath[10:14]
#     print(year)
    month = ix_to_month[filepath[22:24]]
    col = month+year
#     print(col)
    movement_I, movement_D, passengers_I, passengers_D, freight_I, freight_D  = separate_csv(filepath, col)
    
#     print(ix, "------>\n", movement)
#     movement_df.join(movement)
    movement_I_df = movement_I_df.merge(movement_I,how='outer', left_index=True, right_index=True)
    movement_D_df = movement_D_df.merge(movement_D,how='outer', left_index=True, right_index=True)
    
    passengers_I_df = passengers_I_df.merge(passengers_I,how='outer', left_index=True, right_index=True)
    passengers_D_df = passengers_D_df.merge(passengers_D,how='outer', left_index=True, right_index=True)
    
    freight_I_df = freight_I_df.merge(freight_I,how='outer', left_index=True, right_index=True)
    freight_D_df = freight_D_df.merge(freight_D,how='outer', left_index=True, right_index=True)
    
    
#     print(ix,"--\n",movement_df)

In [36]:
allData = {"movement_I_df":movement_I_df,
           "movement_D_df":movement_D_df,
           "passengers_I_df":passengers_I_df,
           "passengers_D_df":passengers_D_df,
           "freight_I_df":freight_I_df,
           "freight_D_df":freight_D_df }

In [37]:
for x in allData.keys():
    print("shape of ", x, "is ", allData[x].shape)

shape of  movement_I_df is  (9, 54)
shape of  movement_D_df is  (9, 54)
shape of  passengers_I_df is  (9, 54)
shape of  passengers_D_df is  (9, 54)
shape of  freight_I_df is  (10, 54)
shape of  freight_D_df is  (10, 54)

In [38]:
allData["movement_I_df"].T.tail(24)

,NaN,NORTH EAST,EASTERN,NORTH EAST,NORTHEN,NORTHERN,SOUTHERN,TOTAL,WESTERN
May2018_I,NaN,NaN,2027,38,NaN,10958,15580,NaN,9233
Jan2018_I,NaN,NaN,2240,34,NaN,11066,15958,NaN,9602
Jul2018_I,NaN,NaN,2021,60,NaN,11428,15347,NaN,9070
Apr2018_I,NaN,NaN,NaN,34,NaN,10649,14810,36441,8943
Jun2018_I,NaN,NaN,1952,36,NaN,10642,14956,NaN,8916
Feb2018_I,NaN,NaN,1934,39,NaN,10054,14020,NaN,8515
Sep2018_I,NaN,NaN,2045,72,NaN,11000,14845,NaN,8995
Oct2018_I,NaN,NaN,2147,79,NaN,11079,15147,NaN,9082
Jun2019_I,15174,NaN,2106,88,NaN,9685,NaN,NaN,7536
Nov2019_I,NaN,NaN,2617,77,NaN,11524,15466,NaN,9025
Apr2019_I,NaN,NaN,2062,56,NaN,9486,15180,NaN,7541
Mar2019_I,NaN,NaN,2333,56,NaN,10671,15488,NaN,9193
Jul2019_I,NaN,NaN,2203,182,NaN,10516,15749,NaN,7970
Dec2019_I,NaN,NaN,2586,69,NaN,12064,16223,NaN,9408
Jan2019_I,NaN,NaN,2435,63,NaN,11811,15780,NaN,10204
Feb2019_I,NaN,NaN,2201,36,NaN,10496,13956,NaN,8931
Aug2019_I,NaN,154,2177,NaN,NaN,10923,15794,NaN,8576
Oct2019_I,NaN,NaN,2450,74,NaN,11656,15610,NaN,8882
Sep2019_I,NaN,104,2199,NaN,NaN,10967,15303,NaN,8628
May2019_I,NaN,NaN,2087,82,NaN,9731,15464,NaN,7630
Apr2020_I,NaN,NaN,165,1,NaN,742,914,NaN,777
Jan2020_I,NaN,NaN,2561,54,NaN,11940,16162,NaN,9351
Mar2020_I,NaN,NaN,1325,26,NaN,6816,8586,NaN,5256
Feb2020_I,NaN,NaN,2275,40,NaN,10856,14677,NaN,8700

In [51]:
# for x,y in allData.items():
#     y.to_csv("../output/"+x+".csv")

In [44]:
# allData['movement_I_df'].loc[['NORTHEN', 'NORTHERN']].T

In [53]:
for x,y in allData.items():
    print("\n")
    print(x)
    
    for xx in y.T.columns:
        print(y[xx].isnull())

movement_I_df

KeyError: nan