In [1]:
import pandas as pd
import numpy as np

In [2]:
import os
import re

allFilePaths = {}

yearList = [int(x) for x in os.listdir('../assets')]

yearList.sort()

# yearList = yearList[:4]

In [3]:

for year in yearList:
    with os.scandir('../assets/'+str(year)) as it:
        for entry in it:
            if entry.name.endswith('.csv') and entry.is_file():
                filename = entry.name
                yearID = int(str(year)+str(filename[7:9]))
                path = '../assets/'+str(year)+'/'+filename
                print(path)
                allFilePaths[yearID] = path

../assets/2016/output-05jun2k16annex5.csv
../assets/2016/output-10nov2k16annex5.csv
../assets/2016/output-07aug2k16annex5.csv
../assets/2016/output-03apr2k16annex5.csv
../assets/2016/output-02mar2k16annex5.csv
../assets/2016/output-09oct2k16annex5.csv
../assets/2016/output-00jan2k16annex5.csv
../assets/2016/output-11dec2k16annex5.csv
../assets/2016/output-04may2k16annex5.csv
../assets/2016/output-01feb2k16annex5.csv
../assets/2016/output-06jul2k16annex5.csv
../assets/2016/output-08sep2k16annex5.csv
../assets/2017/output-01feb2k17annex5.csv
../assets/2017/output-07aug2k17annex5.csv
../assets/2017/output-03apr2k17annex5.csv
../assets/2017/output-05jun2k17annex5.csv
../assets/2017/output-08sep2k17annex5.csv
../assets/2017/output-04may2k17annex5.csv
../assets/2017/output-10nov2k17annex5.csv
../assets/2017/output-09oct2k17annex5.csv
../assets/2017/output-06jul2k17annex5.csv
../assets/2017/output-00jan2k17annex5.csv
../assets/2017/output-02mar2k17annex5.csv
../assets/2017/output-11dec2k17annex5.csv
../assets/2018/output-11dec2k18annex5.csv
../assets/2018/output-07aug2k18annex5.csv
../assets/2018/output-02mar2k18annex5.csv
../assets/2018/output-10nov2k18annex5.csv
../assets/2018/output-04may2k18annex5.csv
../assets/2018/output-00jan2k18annex5.csv
../assets/2018/output-06jul2k18annex5.csv
../assets/2018/output-03apr2k18annex5.csv
../assets/2018/output-05jun2k18annex5.csv
../assets/2018/output-01feb2k18annex5.csv
../assets/2018/output-08sep2k18annex5.csv
../assets/2018/output-09oct2k18annex5.csv
../assets/2019/output-05jun2k19annex5.csv
../assets/2019/output-10nov2k19annex5.csv
../assets/2019/output-03apr2k19annex5.csv
../assets/2019/output-02mar2k19annex5.csv
../assets/2019/output-06jul2k19annex5.csv
../assets/2019/output-11dec2k19annex5.csv
../assets/2019/output-00jan2k19annex5.csv
../assets/2019/output-01feb2k19annex5.csv
../assets/2019/output-07aug2k19annex5.csv
../assets/2019/output-09oct2k19annex5.csv
../assets/2019/output-08sep2k19annex5.csv
../assets/2019/output-04may2k19annex5.csv
../assets/2020/output-03apr2k20annex5.csv
../assets/2020/output-00jan2k20annex5.csv
../assets/2020/output-02mar2k20annex5.csv
../assets/2020/output-01feb2k20annex5.csv

In [4]:
regions = ['EASTERN', 'WESTERN', 'SOUTHERN', 'NORTHERN', 'NORTH EAST']

In [5]:
headers = [x for x in range(19)]

In [6]:
ix_to_month = {
    '00':"Jan",
    '01':"Feb",
    '02':"Mar",
    '03':"Apr",
    '04':"May",
    '05':"Jun",
    '06':"Jul",
    '07':"Aug",
    '08':"Sep",
    '09':"Oct",
    '10':"Nov",
    '11':"Dec"
    
}

In [7]:
def separate_csv(path, yearID):
    df = pd.read_csv(path, names = headers, index_col=False  )
    
    movement = df.iloc[4:4+len(regions)]
    passengers = df.iloc[11:11+len(regions)]
    freight = df.iloc[18:18+len(regions)]
    
    movement_I, movement_D = cleanup(movement, "m",yearID)
    passengers_I, passengers_D = cleanup(passengers, "p",yearID)
    freight_I, freight_D = cleanup(freight, "f",yearID)
    
    return movement_I, movement_D, passengers_I, passengers_D, freight_I, freight_D
#     print(movement.shape)
#     print(passengers.shape)
#     print(freight.shape)

In [8]:
def cleanup(dataframe, name, alt_name):
    dataframe_I = dataframe.loc[:,[0,1]]
    dataframe_D = dataframe.loc[:,[0,7]]
    
    dataframe_I.set_index(0, inplace=True)
    dataframe_D.set_index(0, inplace=True)
    
    dataframe_I.rename(columns={1:alt_name}, inplace=True)
    dataframe_D.rename(columns={7:alt_name}, inplace=True)
    
#     print(dataframe.columns)
#     if name=="m":
#         print(dataframe)
        
    return dataframe_I, dataframe_D

../assets/2017/output-9oct2k17annex5.csv

In [9]:
movement_I_df = pd.DataFrame(index=regions)
passengers_I_df = pd.DataFrame(index=regions)
freight_I_df = pd.DataFrame(index=regions)

movement_D_df = pd.DataFrame(index=regions)
passengers_D_df = pd.DataFrame(index=regions)
freight_D_df = pd.DataFrame(index=regions)

In [10]:

for yearID, filepath in allFilePaths.items():
#     filename = filepath[15:]
# #     print(filename)
#     year = filepath[10:14]
# #     print(year)
#     month = ix_to_month[filepath[22:24]]
#     col = month+year
#     print(col)
    movement_I, movement_D, passengers_I, passengers_D, freight_I, freight_D  = separate_csv(filepath, yearID)
    
#     print(ix, "------>\n", movement)
#     movement_df.join(movement)
    movement_I_df = movement_I_df.merge(movement_I,how='outer', left_index=True, right_index=True)
    movement_D_df = movement_D_df.merge(movement_D,how='outer', left_index=True, right_index=True)
    
    passengers_I_df = passengers_I_df.merge(passengers_I,how='outer', left_index=True, right_index=True)
    passengers_D_df = passengers_D_df.merge(passengers_D,how='outer', left_index=True, right_index=True)
    
    freight_I_df = freight_I_df.merge(freight_I,how='outer', left_index=True, right_index=True)
    freight_D_df = freight_D_df.merge(freight_D,how='outer', left_index=True, right_index=True)
    
    
#     print(ix,"--\n",movement_df)

In [11]:
allData = {"movement_I_df":movement_I_df,
           "movement_D_df":movement_D_df,
           "passengers_I_df":passengers_I_df,
           "passengers_D_df":passengers_D_df,
           "freight_I_df":freight_I_df,
           "freight_D_df":freight_D_df }

In [12]:
for x in allData.keys():
    allData[x] = allData[x].T
    
    allData[x].sort_index(ascending=True, inplace=True)
    print("shape of ", x, "is ", allData[x].shape)

shape of  movement_I_df is  (52, 5)
shape of  movement_D_df is  (52, 5)
shape of  passengers_I_df is  (52, 5)
shape of  passengers_D_df is  (52, 5)
shape of  freight_I_df is  (52, 5)
shape of  freight_D_df is  (52, 5)

In [13]:
allData["movement_I_df"].tail(24)

       EASTERN WESTERN SOUTHERN NORTHERN NORTH EAST
201804    2027    9233    15580    10958         38
201805    1952    8916    14956    10642         36
201806    2021    9070    15347    11428         60
201807    2007    9120    15049    11081         62
201808    2045    8995    14845    11000         72
201809    2147    9082    15147    11079         79
201810    2230    9454    15169    11091         69
201811    2466   10234    15896    11819         39
201900    2435   10204    15780    11811         63
201901    2201    8931    13956    10496         36
201902    2333    9193    15488    10671         56
201903    2062    7541    15180     9486         56
201904    2087    7630    15464     9731         82
201905    2106    7536    15174     9685         88
201906    2203    7970    15749    10516        182
201907   2177    8576     15794    10923        154
201908    2199   8628    15303    10967         104
201909    2450    8882    15610    11656         74
201910    2617    9025    15466    11524         77
201911    2586    9408    16223    12064         69
202000   2561    9351    16162    11940         54
202001    2275    8700    14677    10856         40
202002    1325    5256     8586     6816         26
202003     165     777      914      742          1

In [14]:
allData['movement_I_df'].columns

Index(['EASTERN', 'WESTERN', 'SOUTHERN', 'NORTHERN', 'NORTH EAST'], dtype='object')

In [15]:
for x,y in allData.items():
    print("\n")
    print(x)
    y = pd.to_numeric(y)
    
    for xx in y.columns:
        print(np.sum(pd.isnull(y)))

movement_I_df
EASTERN       0
WESTERN       0
SOUTHERN      0
NORTHERN      0
NORTH EAST    0
dtype: int64
EASTERN       0
WESTERN       0
SOUTHERN      0
NORTHERN      0
NORTH EAST    0
dtype: int64
EASTERN       0
WESTERN       0
SOUTHERN      0
NORTHERN      0
NORTH EAST    0
dtype: int64
EASTERN       0
WESTERN       0
SOUTHERN      0
NORTHERN      0
NORTH EAST    0
dtype: int64
EASTERN       0
WESTERN       0
SOUTHERN      0
NORTHERN      0
NORTH EAST    0
dtype: int64


movement_D_df
EASTERN       0
WESTERN       0
SOUTHERN      0
NORTHERN      0
NORTH EAST    0
dtype: int64
EASTERN       0
WESTERN       0
SOUTHERN      0
NORTHERN      0
NORTH EAST    0
dtype: int64
EASTERN       0
WESTERN       0
SOUTHERN      0
NORTHERN      0
NORTH EAST    0
dtype: int64
EASTERN       0
WESTERN       0
SOUTHERN      0
NORTHERN      0
NORTH EAST    0
dtype: int64
EASTERN       0
WESTERN       0
SOUTHERN      0
NORTHERN      0
NORTH EAST    0
dtype: int64


passengers_I_df
EASTERN       0
WESTERN       0
SOUTHERN      0
NORTHERN      0
NORTH EAST    0
dtype: int64
EASTERN       0
WESTERN       0
SOUTHERN      0
NORTHERN      0
NORTH EAST    0
dtype: int64
EASTERN       0
WESTERN       0
SOUTHERN      0
NORTHERN      0
NORTH EAST    0
dtype: int64
EASTERN       0
WESTERN       0
SOUTHERN      0
NORTHERN      0
NORTH EAST    0
dtype: int64
EASTERN       0
WESTERN       0
SOUTHERN      0
NORTHERN      0
NORTH EAST    0
dtype: int64


passengers_D_df
EASTERN       0
WESTERN       0
SOUTHERN      0
NORTHERN      0
NORTH EAST    0
dtype: int64
EASTERN       0
WESTERN       0
SOUTHERN      0
NORTHERN      0
NORTH EAST    0
dtype: int64
EASTERN       0
WESTERN       0
SOUTHERN      0
NORTHERN      0
NORTH EAST    0
dtype: int64
EASTERN       0
WESTERN       0
SOUTHERN      0
NORTHERN      0
NORTH EAST    0
dtype: int64
EASTERN       0
WESTERN       0
SOUTHERN      0
NORTHERN      0
NORTH EAST    0
dtype: int64


freight_I_df
EASTERN       0
WESTERN       0
SOUTHERN      0
NORTHERN      0
NORTH EAST    0
dtype: int64
EASTERN       0
WESTERN       0
SOUTHERN      0
NORTHERN      0
NORTH EAST    0
dtype: int64
EASTERN       0
WESTERN       0
SOUTHERN      0
NORTHERN      0
NORTH EAST    0
dtype: int64
EASTERN       0
WESTERN       0
SOUTHERN      0
NORTHERN      0
NORTH EAST    0
dtype: int64
EASTERN       0
WESTERN       0
SOUTHERN      0
NORTHERN      0
NORTH EAST    0
dtype: int64


freight_D_df
EASTERN       0
WESTERN       0
SOUTHERN      0
NORTHERN      0
NORTH EAST    0
dtype: int64
EASTERN       0
WESTERN       0
SOUTHERN      0
NORTHERN      0
NORTH EAST    0
dtype: int64
EASTERN       0
WESTERN       0
SOUTHERN      0
NORTHERN      0
NORTH EAST    0
dtype: int64
EASTERN       0
WESTERN       0
SOUTHERN      0
NORTHERN      0
NORTH EAST    0
dtype: int64
EASTERN       0
WESTERN       0
SOUTHERN      0
NORTHERN      0
NORTH EAST    0
dtype: int64

In [16]:
for x,y in allData.items():
    y.to_csv("../output/"+x+".csv")